export const LOAD_MORE_NOW_PLAYING_MOVIES =
  'LOAD_MORE_NOW_PLAYING_MOVIES';
export const LOAD_MORE_POPULAR_MOVIES =
  'LOAD_MORE_POPULAR_MOVIES';
export const LOAD_MORE_TOP_RATED_MOVIES =
  'LOAD_MORE_TOP_RATED_MOVIES';
export const LOAD_MORE_UPCOMING_MOVIES =
  'LOAD_MORE_UPCOMING_MOVIES';
export const SET_ERROR = 'SET_ERROR';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_LOADING = 'SET_LOADING';
export const SET_NOW_PLAYING_MOVIE_LIST =
  'SET_NOW_PLAYING_MOVIE_LIST';
export const SET_NOW_PLAYING_PAGE = 'SET_NOW_PLAYING_PAGE';
export const SET_NOW_PLAYING_SLIDESHOW_PICTURES =
  'SET_NOW_PLAYING_SLIDESHOW_PICTURES';
export const SET_PAGE = 'SET_PAGE';
export const SET_POPULAR_MOVIE_LIST =
  'SET_POPULAR_MOVIE_LIST';
export const SET_POPULAR_PAGE = 'SET_POPULAR_PAGE';
export const SET_POPULAR_SLIDESHOW_PICTURES =
  'SET_POPULAR_SLIDESHOW_PICTURES';
export const SET_QUERY = 'SET_QUERY';
export const SET_THEME = 'SET_THEME';
export const SET_TOP_RATED_MOVIE_LIST =
  'SET_TOP_RATED_MOVIE_LIST';
export const SET_TOP_RATED_PAGE = 'SET_TOP_RATED_PAGE';
export const SET_TOP_RATED_SLIDESHOW_PICTURES =
  'SET_TOP_RATED_SLIDESHOW_PICTURES';
export const SET_UPCOMING_MOVIE_LIST =
  'SET_UPCOMING_MOVIE_LIST';
export const SET_UPCOMING_PAGE = 'SET_UPCOMING_PAGE';
export const SET_UPCOMING_SLIDESHOW_PICTURES =
  'SET_UPCOMING_SLIDESHOW_PICTURES';
