export const SET_ERROR = 'SET_ERROR';
export const SET_POPULAR_MOVIE_LIST =
  'SET_POPULAR_MOVIE_LIST';
export const SET_PAGE = 'SET_PAGE';
export const SET_SLIDESHOW_PICTURES =
  'SET_SLIDESHOW_PICTURES';
export const SET_NOW_PLAYING_MOVIE_LIST =
  'SET_NOW_PLAYING_MOVIE_LIST';
